### ISSUE TITLE
Slack badge and link in README are broken

### ISSUE THREAD

**Issue by davidxia** [freelawproject/related-literature#4]
The status badge at the top and link at the bottom of https://github.com/freelawproject/related-literature/blob/master/README.md are broken. I'll gladly make a PR to update if someone lets me know the right link.

But maybe contact details in the README should be updated to say contact the admins so they can invite you to the Slack workspace or something.

**Comment by mlissner** [comment]
Shoot, yeah that slack bridge turned out to be a bad idea. For whatever reason, the heroku server kept breaking. Anyway, yeah, if you want to just tweak this to say, "here's our contact info" or whatever, that'd be great.
